### ISSUE TITLE
Disassemble tool

### ISSUE THREAD

**Issue by Dutisto** [KevOrr/ctf-writeups#1]
Hello,
You made really good writeups. I was wondering what is the tool you used for disassembling the binaries, if you could tell me.

Nice work !

**Comment by KevOrr** [comment]
Hey! Glad they're of use to someone! I personally use [Binary Ninja](https://binary.ninja/). I absolutely love it, but it's $150. I used to recommend their free trial to people, but I hesitate to do that anymore, since now you can only use it for 25 minutes at a time, and you can't save your edits. Instead of the trial that you run locally, they have a ["cloud"](https://cloud.binary.ninja/) version (read: a web app) that's totally free, it's just stripped down to the basics.

Also there's [Ghidra](https://ghidra-sre.org/) which is [open source](https://github.com/NationalSecurityAgency/ghidra) and free. It has quickly gained popularity, though I've used it very little. If you do use it, check out the [GhidraDocs/GhidraClass](https://github.com/NationalSecurityAgency/ghidra/tree/master/GhidraDocs/GhidraClass) directory, it's quite nice.

**Comment by KevOrr** [comment]
Going to close this for now. If you have any questions, just holler!
